# Generated by Django 4.2.3 on 2023-07-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grostena_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoservisas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_lat', models.FloatField(verbose_name=54.73439)),
                ('location_lon', models.FloatField(verbose_name=25.254407)),
                ('service', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='KEMI',
        ),
    ]