# Generated by Django 4.2.3 on 2023-07-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grostena_app', '0002_autoservisas_delete_kemi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoservisas',
            name='location_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='autoservisas',
            name='location_lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='autoservisas',
            name='service',
            field=models.CharField(choices=[('Variklio skyrius', 'Pakaba'), ('elektros drbai', 'Diagnostika'), ('Dazymas', 'Kebulo darbai'), ('Padangu remontas', 'Ratai'), ('Diagnostika', 'Lemputes skydelyje')], max_length=100),
        ),
    ]