# Generated by Django 4.2.4 on 2023-08-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grostena_app', '0005_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RenameField(
            model_name='autoservice',
            old_name='latitude',
            new_name='location_lat',
        ),
        migrations.RenameField(
            model_name='autoservice',
            old_name='longitude',
            new_name='location_lon',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='autoservice',
            name='category',
        ),
        migrations.AddField(
            model_name='autoservice',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoservice',
            name='working_hours',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repaircategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]