# Generated by Django 4.2.3 on 2023-08-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grostena_app', '0006_delete_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoservice',
            name='category',
            field=models.ManyToManyField(to='Grostena_app.repaircategory'),
        ),
    ]