# Generated by Django 4.2.3 on 2023-08-03 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Grostena_app', '0007_autoservice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoservice',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoservice',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]