# Generated by Django 4.2.3 on 2023-08-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grostena_app', '0009_rename_category_autoservice_repair_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoservice',
            name='description',
        ),
        migrations.AlterField(
            model_name='autoservice',
            name='location_lat',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='autoservice',
            name='location_lon',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='autoservice',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='autoservice',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='repaircategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]