# Generated by Django 4.2.4 on 2023-08-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grostena_app', '0012_alter_autoservice_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoservice',
            name='category',
        ),
        migrations.AddField(
            model_name='autoservice',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='Grostena_app.repaircategory'),
        ),
    ]
